### ISSUE TITLE
[ui] ensure the responsive of box/matrix displayed on home page 

### ISSUE THREAD

**Issue by Yana-Gupta** [Yana-Gupta/trade-off#1]
At certain viewpoint the responsiveness of these boxes are breaking

![image](https://github.com/Yana-Gupta/trade-off/assets/103108630/38fc8039-a35a-4fcf-8e86-9b942f190c5b)

You have to ensure that it is not breaking at any point

**Comment by IrfanshaikH-7** [comment]
I would like to work on this can you assign me to this issue!

**Comment by krishpatel023** [comment]
It would be better to just change the layout from horizontal to vertical at that point.

**Comment by IrfanshaikH-7** [comment]
Yes ! for smaller devices they won't fit properly. I'll look into it, and I'll send a screenshot before confirming the layout in comment.

**Comment by Yana-Gupta** [comment]
Following FCFS, assigned to @IrfanshaikH-7

**Comment by Yana-Gupta** [comment]
@IrfanshaikH-7 I am closing this, you can find other issues till then.

Thanks to both of you for volunteering 👏🏼

**Comment by Yana-Gupta** [comment]
@IrfanshaikH-7 You can make a PR now 

@krishpatel023 your changes made a distortion please confirm the changes before making a PR, and also please avoid making PR if the issue is assigned to another person. 

![image](https://github.com/Yana-Gupta/trade-off/assets/103108630/e90d8de0-05d2-483f-946a-1d66b3a9b2c0)

**Comment by IrfanshaikH-7** [comment]
Mmm! I finished doing it. just know!

**Comment by IrfanshaikH-7** [comment]
Sure lemmi  send some Screenshot for confirmation

**Comment by IrfanshaikH-7** [comment]
![Screenshot 2023-10-01 232532](https://github.com/Yana-Gupta/trade-off/assets/124655192/beec8c42-7b2d-4750-a944-f0d861a09c6e)
![Screenshot 2023-10-01 232802](https://github.com/Yana-Gupta/trade-off/assets/124655192/23d82687-5fab-43a1-b52a-69ed45b5035f)
![Screenshot 20
![Screenshot 2023-10-02 001447](https://github.com/Yana-Gupta/trade-off/assets/124655192/ff70af65-3e97-48e8-84ae-51d8ecb9b3af)
23-10-02 001002](https://github.com/Yana-Gupta/trade-off/assets/124655192/09c3c63c-af17-4d4a-95cd-bfb86f44851e)

Review them and if you find anything out of place tell me !

**Comment by Yana-Gupta** [comment]
The ethereum card should have a fixed max-width property, in the last image that you sent it is distorting horizontally too much I think you have used the same approach as @krishpatel023 .

**Comment by Yana-Gupta** [comment]
Make sure whatever changes you are making to make that box responsive your changes should not affect the card 

![image](https://github.com/Yana-Gupta/trade-off/assets/103108630/28998914-a9aa-4d70-9351-a23ef6fa4b02)

Btw you both have put some good work. Thanks for it  🙌🏼

**Comment by IrfanshaikH-7** [comment]
hello! i found a issue and solved it can i Pr again ! for that minor fix
